algoritmo "Exercicio091"
var
   N1, N2: Inteiro
Procedimento Maior (A,B: Inteiro)
inicio
      Se A > B entao
         Escreval ("O maior número é", A)
      FimSe
      Se B > A entao
         Escreval ("O maior número é", B)
      FimSe
      Se A  =B entao
         Escreval ("Os dois valores são iguais")
      FimSe
FimProcedimento
inicio
      Escreva ("Digite o primeiro valor: ")
      Leia (N1)
      Escreva ("Digite o segundo valor: ")
      Leia (N2)
      Maior (N1,N2)
fimalgoritmo